### PR TITLE
rename oidc outputs

### PR DESCRIPTION
**Pull request by ettiee**
Replaces #169

### CODE REVIEW

**Comment by errm** [comment]
I should have fixed the linting issue on master ... if you rebase everything should be green!

**Comment by ettiee** [comment]
@dan-slinky-ckpd @aidy can you take a 👀 on this check you're happy for the stable 1.18 cut - it's a breaking configuration change (very minor) for teams upgrading

**Review by aidy — APPROVED** [review]
LGTM

**Review by dan-slinky-ckpd — APPROVED** [review]
LGTM. Lets get an update to https://github.com/cookpad/terraform-aws-eks/blob/master/UPGRADING.md asap though, so we don't forget.

**Pull request merged**
