### PR TITLE
remove load-balancer-controller and ingress tests

### PR DESCRIPTION
**Pull request by ettiee**
Contributes #224
- Remove aws-load-balancer-controller from cluster addons
- Remove validateIngress test

### CODE REVIEW

**Comment by mtpereira** [comment]
:heavy_check_mark: Change looks good!

:croissant: Re-running flaky tests.

**Comment by aidy** [comment]
I think we should add some context to the commit messages here - I can see what they're doing, but it's unclear what the motivation is.

**Comment by aidy** [comment]
Suggest that we squash these three commits together with a commit message something like:

```
Remove load-balancer-controller

We've decided to remove non-critical addons from this module.
Rather than try to provide a one-size-fits-all setup, we're changing focus to provide a
minimal setup, and expect that users will use another mechanism for additional configuration. 
```

(`remove load-balancer-controller and ingress tests` is unclear English. Could read as `load-balancer-controller tests and ingress tests` or `ingress tests and load-balancer-controller` - but I think removing the tests here is a facet of removing the load-balancer-controller, rather than explicit change in it's own right)

**Comment by ettiee** [comment]
@aidy sure makes sense - could you check the latest squashed commit

**Review by mtpereira — APPROVED** [review]
:rocket:

**Pull request merged**
