### PR TITLE
[IAM module] Fix Invalid depends_on reference error

### PR DESCRIPTION
**Pull request by takanabe**
## Background

The following error occurs while terraform plan is executed.

<details>
<summary>terraform plan</summary>

```
terraform plan
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...

Error: Invalid depends_on reference

  on .terraform/modules/eks_iam/modules/iam/outputs.tf line 7, in output "config":
   7:     aws_iam_role_policy_attachment.eks_worker_node.policy_arn,

References in depends_on must be to a whole object (resource, etc), not to an
attribute of an object.

Error: Invalid depends_on reference

  on .terraform/modules/eks_iam/modules/iam/outputs.tf line 8, in output "config":
   8:     aws_iam_role_policy_attachment.eks_cni.policy_arn,

References in depends_on must be to a whole object (resource, etc), not to an
attribute of an object.

Error: Invalid depends_on reference

  on .terraform/modules/eks_iam/modules/iam/outputs.tf line 9, in output "config":
   9:     aws_iam_role_policy_attachment.ecr.policy_arn,

References in depends_on must be to a whole object (resource, etc), not to an
attribute of an object.

Error: Invalid depends_on reference

  on .terraform/modules/eks_iam/modules/iam/outputs.tf line 10, in output "config":
  10:     aws_iam_role_policy_attachment.eks_service_policy.policy_arn,

References in depends_on must be to a whole object (resource, etc), not to an
attribute of an object.

Error: Invalid depends_on reference

  on .terraform/modules/eks_iam/modules/iam/outputs.tf line 11, in output "config":
  11:     aws_iam_role_policy_attachment.eks_cluster_policy.policy_arn,

References in depends_on must be to a whole object (resource, etc), not to an
```
</details>

To fix this invalid dependency errors, we have to pass objects instead of resouces(policy_arn.)

## Technical changes

* Pass objects instead of resouces(policy_arn) to `depends_on` argument.

## Test Environment

A clean AWS account with the following Terraform configurations.

```
$ cat main.tf
module "eks_iam" {
  source  = "cookpad/eks/aws//modules/iam"
  version = "1.17.0"
}

$ cat .terraform-version
0.14.5
```

## Terraform plan with this PR

<details>
<summary>terraform plan</summary>

```
$ terraform plan
Acquiring state lock. This may take a few moments...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.eks_iam.aws_iam_instance_profile.eks_node will be created
  + resource "aws_iam_instance_profile" "eks_node" {
      + arn         = (known after apply)
      + create_date = (known after apply)
      + id          = (known after apply)
      + name        = "EKSNode"
      + path        = "/"
      + role        = "EKSNode"
      + unique_id   = (known after apply)
    }

  # module.eks_iam.aws_iam_role.eks_node will be created
  + resource "aws_iam_role" "eks_node" {
      + arn                   = (known after apply)
      + assume_role_policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "sts:AssumeRole"
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "ec2.amazonaws.com"
                        }
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + max_session_duration  = 3600
      + name                  = "EKSNode"
      + path                  = "/"
      + unique_id             = (known after apply)
    }

  # module.eks_iam.aws_iam_role.eks_service_role will be created
  + resource "aws_iam_role" "eks_service_role" {
      + arn                   = (known after apply)
      + assume_role_policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "sts:AssumeRole"
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "eks.amazonaws.com"
                        }
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + max_session_duration  = 3600
      + name                  = "eksServiceRole"
      + path                  = "/"
      + unique_id             = (known after apply)
    }

  # module.eks_iam.aws_iam_role_policy.set_name_tag will be created
  + resource "aws_iam_role_policy" "set_name_tag" {
      + id     = (known after apply)
      + name   = "set_name_tag"
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "ec2:CreateTags",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + role   = (known after apply)
    }

  # module.eks_iam.aws_iam_role_policy_attachment.ecr will be created
  + resource "aws_iam_role_policy_attachment" "ecr" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      + role       = "EKSNode"
    }

  # module.eks_iam.aws_iam_role_policy_attachment.eks_cluster_policy will be created
  + resource "aws_iam_role_policy_attachment" "eks_cluster_policy" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
      + role       = "eksServiceRole"
    }

  # module.eks_iam.aws_iam_role_policy_attachment.eks_cni will be created
  + resource "aws_iam_role_policy_attachment" "eks_cni" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
      + role       = "EKSNode"
    }

  # module.eks_iam.aws_iam_role_policy_attachment.eks_service_policy will be created
  + resource "aws_iam_role_policy_attachment" "eks_service_policy" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"
      + role       = "eksServiceRole"
    }

  # module.eks_iam.aws_iam_role_policy_attachment.eks_worker_node will be created
  + resource "aws_iam_role_policy_attachment" "eks_worker_node" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
      + role       = "EKSNode"
    }

  # module.eks_iam.aws_iam_role_policy_attachment.ssm_managed_instance_core will be created
  + resource "aws_iam_role_policy_attachment" "ssm_managed_instance_core" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
      + role       = "EKSNode"
    }

Plan: 10 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

Releasing state lock. This may take a few moments...

```
</details>

### CODE REVIEW

**Comment by takanabe** [comment]
@dan-slinky-ckpd @ettiee @aidy any chance to get reviews on this PR 🤔 ?

**Review by ettiee — APPROVED** [review]

**Comment by mtpereira** [comment]
Tests failed, I've re-runned them to check it was a flaky test or there is actually a problem.

**Review by mtpereira — CHANGES_REQUESTED** [review]
Tests are failing, don't know if it is related to the change but we should definitely check!

**Comment by dan-slinky-ckpd** [comment]
can you rebase off latest master ?

**Comment by ettiee** [comment]
> Tests are failing, don't know if it is related to the change but we should definitely check!

👍 CI was broken but should be fixed by https://github.com/cookpad/terraform-aws-eks/pull/179

**Comment by takanabe** [comment]
I rebased the latest master but the test is still failing... although my change does not affect the test result.

image

**Comment by ettiee** [comment]
Seems to be an issue with the nslookup- Job https://github.com/cookpad/terraform-aws-eks/pull/185/checks?check_run_id=1878980648#step:4:801

**Comment by errm** [comment]
Test issue can’t be caused by this change... we don’t use the IAM module in the tests... Perhaps we should add a test for it though?

**Comment by takanabe** [comment]
@ettiee thank you! seems the test works now!

**Pull request merged**
