### PR TITLE
Manage vpc-cni, coredns and kube-proxy via eks addons

### PR DESCRIPTION
**Pull request by aidy**

### CODE REVIEW

**Review by ettiee — APPROVED** [review]
lgtm - could you update the PR description before merging?

**Comment by ettiee** [comment]
989ef33db0e9839cfac1da69880f334bc9586283 removes a variable so probably worth documenting in `UPGRADING.md`

**Comment by aidy** [comment]
> lgtm - could you update the PR description before merging?

hmm, so - my normal approach is to have sane, atomic, commits - and then to merge the commits, rather than squash.

Perhaps it's worth rewording 821d95f to have some reasoning for the motivation for this change. Would that work for you?

**Comment by ettiee** [comment]
> Perhaps it's worth rewording [821d95f](https://github.com/cookpad/terraform-aws-eks/commit/821d95f20be19128903adf6ea83c803ff8b000c3) to have some reasoning for the motivation for this change. Would that work for you?

Yes that sounds good 👍 
And also link the related issues in the PR? (#224 and #256) for easy reference from the issues?

**Review by ettiee — APPROVED** [review]
lgtm - be good to include https://github.com/cookpad/terraform-aws-eks/pull/276#issuecomment-981795919

**Comment by aidy** [comment]
> lgtm - be good to include #276 (comment)

Oh, yes.

**Pull request merged**
