### PR TITLE
Manage vpc-cni, coredns and kube-proxy via eks addons

### PR DESCRIPTION
**Pull request by errm**
https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html

### CODE REVIEW

**Comment by errm** [comment]
Makes a start on #224

**Comment by errm** [comment]
📝 This seems to not work well, I am hitting this error every time I try to apply.

```
Error: unexpected EKS Add-On (terraform-aws-eks-testing-jPfg0J:coredns) state returned during creation: unexpected state 'DEGRADED', wanted target 'ACTIVE'. last error: %!!(MISSING)s(<nil>)
```

I will loop back to this and test again on 1.20 or 1.21

**Comment by takanabe** [comment]
@errm Do you have any progresses on the PR? If not I will take a look at this 👀

**Comment by aidy** [comment]
fyi I'm poking about with this in #276

**Comment by aidy** [comment]
Closing in favour of #276

**Pull request closed without merging**
